# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Documents/python_projects/abrasion_gui/mainWindow.ui'
#
# Created: Wed May  3 14:43:55 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(777, 703)
        self.mainPlot = QtWidgets.QVBoxLayout(mainWindow)
##        self.mainPlot.setContentsMargins(0, 0, 0, 0)
        self.mainPlot.setGeometry(QtCore.QRect(10, 261, 751, 311))
        self.mainPlot.setObjectName("mainPlotBox")
        self.figure = plt.figure(dpi=80)
        self.mainPlotFig = FigureCanvas(self.figure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPlotFig.sizePolicy().hasHeightForWidth())
        self.mainPlotFig.setGeometry(QtCore.QRect(10, 261, 751, 311))
        self.mainPlotFig.setSizePolicy(sizePolicy)
        self.mainPlotFig.setMaximumSize(QtCore.QSize(741, 311))
        self.mainPlotFig.setObjectName("mainPlot")
        self.mainPlot.addWidget(self.mainPlotFig)
        self.consoleBox = QtWidgets.QGroupBox(mainWindow)
        self.consoleBox.setGeometry(QtCore.QRect(10, 570, 751, 131))
        self.consoleBox.setObjectName("consoleBox")
        self.console = QtWidgets.QTextEdit(self.consoleBox)
        self.console.setGeometry(QtCore.QRect(0, 20, 741, 101))
        self.console.setObjectName("console")
        self.console.setReadOnly(True)
        self.splitter = QtWidgets.QSplitter(mainWindow)
        self.splitter.setGeometry(QtCore.QRect(10, 180, 751, 71))
        self.splitter.setMinimumSize(QtCore.QSize(741, 71))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.outputWidget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputWidget.sizePolicy().hasHeightForWidth())
        self.outputWidget.setSizePolicy(sizePolicy)
        self.outputWidget.setMinimumSize(QtCore.QSize(451, 0))
        self.outputWidget.setObjectName("outputWidget")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.outputWidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 20, 441, 35))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.outDirLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.outDirLayout.setContentsMargins(0, 0, 0, 0)
        self.outDirLayout.setObjectName("outDirLayout")
        self.outDirLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.outDirLabel.setObjectName("outDirLabel")
        self.outDirLayout.addWidget(self.outDirLabel)
        self.outDirInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.outDirInput.setObjectName("outDirInput")
        self.outDirInput.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("\\/(.+\\/)*$")))
        self.outDirLayout.addWidget(self.outDirInput)
        self.browseButton = QtWidgets.QToolButton(self.horizontalLayoutWidget_7)
        self.browseButton.setObjectName("browseButton")
        self.outDirLayout.addWidget(self.browseButton)
        self.realTimeBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.realTimeBox.sizePolicy().hasHeightForWidth())
        self.realTimeBox.setSizePolicy(sizePolicy)
        self.realTimeBox.setMinimumSize(QtCore.QSize(271, 0))
        self.realTimeBox.setObjectName("realTimeBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.realTimeBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 20, 51, 50))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.realTimeLayout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.realTimeLayout2.setContentsMargins(0, 0, 0, 0)
        self.realTimeLayout2.setObjectName("realTimeLayout2")
        self.realHLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.realHLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.realHLabel.setObjectName("realHLabel")
        self.realTimeLayout2.addWidget(self.realHLabel)
        self.realHDisplay = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.realHDisplay.setText("")
        self.realHDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.realHDisplay.setObjectName("realHDisplay")
        self.realTimeLayout2.addWidget(self.realHDisplay)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.realTimeBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 53, 50))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.realTimeLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.realTimeLayout1.setContentsMargins(0, 0, 0, 0)
        self.realTimeLayout1.setObjectName("realTimeLayout1")
        self.realULabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.realULabel.setAlignment(QtCore.Qt.AlignCenter)
        self.realULabel.setObjectName("realULabel")
        self.realTimeLayout1.addWidget(self.realULabel)
        self.realUDisplay = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.realUDisplay.setText("")
        self.realUDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.realUDisplay.setObjectName("realUDisplay")
        self.realTimeLayout1.addWidget(self.realUDisplay)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.realTimeBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 20, 60, 50))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.realTimeLayout3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.realTimeLayout3.setContentsMargins(0, 0, 0, 0)
        self.realTimeLayout3.setObjectName("realTimeLayout3")
        self.timeElapsedLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.timeElapsedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeElapsedLabel.setObjectName("timeElapsedLabel")
        self.realTimeLayout3.addWidget(self.timeElapsedLabel)
        self.timeElapsedDisplay = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.timeElapsedDisplay.setText("")
        self.timeElapsedDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.timeElapsedDisplay.setObjectName("timeElapsedDisplay")
        self.realTimeLayout3.addWidget(self.timeElapsedDisplay)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.realTimeBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(200, 20, 65, 50))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.realTimeLayout3_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.realTimeLayout3_2.setContentsMargins(0, 0, 0, 0)
        self.realTimeLayout3_2.setObjectName("realTimeLayout3_2")
        self.tempLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.tempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel.setObjectName("tempLabel")
        self.realTimeLayout3_2.addWidget(self.tempLabel)
        self.tempDisplay = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.tempDisplay.setText("")
        self.tempDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.tempDisplay.setObjectName("tempDisplay")
        self.realTimeLayout3_2.addWidget(self.tempDisplay)
        self.splitter_2 = QtWidgets.QSplitter(mainWindow)
        self.splitter_2.setGeometry(QtCore.QRect(10, 10, 751, 171))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.sustainedSettings = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sustainedSettings.sizePolicy().hasHeightForWidth())
        self.sustainedSettings.setSizePolicy(sizePolicy)
        self.sustainedSettings.setMinimumSize(QtCore.QSize(201, 171))
        self.sustainedSettings.setObjectName("sustainedSettings")
        self.sustainedStartButton = QtWidgets.QPushButton(self.sustainedSettings)
        self.sustainedStartButton.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.sustainedStartButton.setObjectName("sustainedStartButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.sustainedSettings)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 201, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.targetULayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.targetULayout.setContentsMargins(0, 0, 0, 0)
        self.targetULayout.setObjectName("targetULayout")
        self.targetULabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.targetULabel.setObjectName("targetULabel")
        self.targetULayout.addWidget(self.targetULabel)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setValidator(QtGui.QDoubleValidator(bottom=0.,top=2.))
        self.targetULayout.addWidget(self.lineEdit)
        self.targetUUnits = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.targetUUnits.setObjectName("targetUUnits")
        self.targetULayout.addWidget(self.targetUUnits)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.sustainedSettings)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 90, 201, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.actualULayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.actualULayout.setContentsMargins(0, 0, 0, 0)
        self.actualULayout.setObjectName("actualULayout")
        self.actualULabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.actualULabel.setObjectName("actualULabel")
        self.actualULayout.addWidget(self.actualULabel)
        self.actualUDisplay = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.actualUDisplay.setText("")
        self.actualUDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.actualUDisplay.setObjectName("actualUDisplay")
        self.actualULayout.addWidget(self.actualUDisplay)
        self.actualUUnits = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.actualUUnits.setObjectName("actualUUnits")
        self.actualULayout.addWidget(self.actualUUnits)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.sustainedSettings)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 130, 201, 35))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.targetULayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.targetULayout_3.setContentsMargins(0, 0, 0, 0)
        self.targetULayout_3.setObjectName("targetULayout_3")
        self.targetTimeLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.targetTimeLabel.setObjectName("targetTimeLabel")
        self.targetULayout_3.addWidget(self.targetTimeLabel)
        self.targetTimeEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.targetTimeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetTimeEdit.setObjectName("targetTimeEdit")
        self.targetTimeEdit.setValidator(QtGui.QDoubleValidator(bottom=0.))
        self.targetULayout_3.addWidget(self.targetTimeEdit)
        self.targetTimeUnits = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.targetTimeUnits.setObjectName("targetTimeUnits")
        self.targetULayout_3.addWidget(self.targetTimeUnits)
        self.periodSettings = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodSettings.sizePolicy().hasHeightForWidth())
        self.periodSettings.setSizePolicy(sizePolicy)
        self.periodSettings.setMinimumSize(QtCore.QSize(201, 161))
        self.periodSettings.setObjectName("periodSettings")
        self.periodStartButton = QtWidgets.QPushButton(self.periodSettings)
        self.periodStartButton.setGeometry(QtCore.QRect(70, 20, 75, 23))
        self.periodStartButton.setObjectName("periodStartButton")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.periodSettings)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 50, 201, 35))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.targetTLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.targetTLayout.setContentsMargins(0, 0, 0, 0)
        self.targetTLayout.setObjectName("targetTLayout")
        self.targetTLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.targetTLabel.setObjectName("targetTLabel")
        self.targetTLayout.addWidget(self.targetTLabel)
        self.targetTEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.targetTEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetTEdit.setObjectName("targetTEdit")
        self.targetTEdit.setValidator(QtGui.QIntValidator(0,10))
        self.targetTLayout.addWidget(self.targetTEdit)
        self.targetTUnits = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.targetTUnits.setObjectName("targetTUnits")
        self.targetTLayout.addWidget(self.targetTUnits)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.periodSettings)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 90, 201, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.actualTLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.actualTLayout.setContentsMargins(0, 0, 0, 0)
        self.actualTLayout.setObjectName("actualTLayout")
        self.actualTLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.actualTLabel.setObjectName("actualTLabel")
        self.actualTLayout.addWidget(self.actualTLabel)
        self.actualTDisplay = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.actualTDisplay.setText("")
        self.actualTDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.actualTDisplay.setObjectName("actualTDisplay")
        self.actualTLayout.addWidget(self.actualTDisplay)
        self.actualTUnits = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.actualTUnits.setObjectName("actualTUnits")
        self.actualTLayout.addWidget(self.actualTUnits)
        self.paramTabs = QtWidgets.QTabWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramTabs.sizePolicy().hasHeightForWidth())
        self.paramTabs.setSizePolicy(sizePolicy)
        self.paramTabs.setMinimumSize(QtCore.QSize(331, 161))
        self.paramTabs.setObjectName("paramTabs")
        self.physicalTab = QtWidgets.QWidget()
        self.physicalTab.setObjectName("physicalTab")
        self.densityLabel = QtWidgets.QLabel(self.physicalTab)
        self.densityLabel.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.densityLabel.setObjectName("densityLabel")
        self.densityEdit = QtWidgets.QLineEdit(self.physicalTab)
        self.densityEdit.setGeometry(QtCore.QRect(210, 10, 113, 20))
        self.densityEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.densityEdit.setObjectName("densityEdit")
        self.densityEdit.setValidator(QtGui.QDoubleValidator(bottom=900.,top=1200.))
        self.areaFactorLabel = QtWidgets.QLabel(self.physicalTab)
        self.areaFactorLabel.setGeometry(QtCore.QRect(10, 30, 161, 16))
        self.areaFactorLabel.setObjectName("areaFactorLabel")
        self.areaFactorEdit = QtWidgets.QLineEdit(self.physicalTab)
        self.areaFactorEdit.setGeometry(QtCore.QRect(210, 30, 113, 20))
        self.areaFactorEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.areaFactorEdit.setObjectName("areaFactorEdit")
        self.areaFactorEdit.setValidator(QtGui.QDoubleValidator(bottom=0.))
        self.paramTabs.addTab(self.physicalTab, "")
        self.numericalTab = QtWidgets.QWidget()
        self.numericalTab.setObjectName("numericalTab")
        self.fbackVelLabel = QtWidgets.QLabel(self.numericalTab)
        self.fbackVelLabel.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.fbackVelLabel.setObjectName("fbackVelLabel")
        self.fbackVelEdit = QtWidgets.QLineEdit(self.numericalTab)
        self.fbackVelEdit.setGeometry(QtCore.QRect(220, 10, 101, 20))
        self.fbackVelEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.fbackVelEdit.setObjectName("fbackVelEdit")
        self.fbackVelEdit.setValidator(QtGui.QDoubleValidator(bottom=0.))
        self.fbackAccLabel = QtWidgets.QLabel(self.numericalTab)
        self.fbackAccLabel.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.fbackAccLabel.setObjectName("fbackAccLabel")
        self.fbackAccEdit = QtWidgets.QLineEdit(self.numericalTab)
        self.fbackAccEdit.setGeometry(QtCore.QRect(220, 30, 101, 20))
        self.fbackAccEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.fbackAccEdit.setObjectName("fbackAccEdit")
        self.fbackAccEdit.setValidator(QtGui.QDoubleValidator(bottom=0.))
        self.pressureSampleLabel = QtWidgets.QLabel(self.numericalTab)
        self.pressureSampleLabel.setGeometry(QtCore.QRect(10, 50, 181, 16))
        self.pressureSampleLabel.setObjectName("pressureSampleLabel")
        self.pressureSampleEdit = QtWidgets.QLineEdit(self.numericalTab)
        self.pressureSampleEdit.setGeometry(QtCore.QRect(220, 50, 101, 20))
        self.pressureSampleEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pressureSampleEdit.setObjectName("pressureSampleEdit")
        self.pressureSampleEdit.setValidator(QtGui.QDoubleValidator(bottom=0.,top=1000.))
        self.sinSampleLabel = QtWidgets.QLabel(self.numericalTab)
        self.sinSampleLabel.setGeometry(QtCore.QRect(10, 70, 191, 16))
        self.sinSampleLabel.setObjectName("sinSampleLabel")
        self.sinSampleEdit = QtWidgets.QLineEdit(self.numericalTab)
        self.sinSampleEdit.setGeometry(QtCore.QRect(222, 70, 101, 20))
        self.sinSampleEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sinSampleEdit.setObjectName("sinSampleEdit")
        self.sinSampleEdit.setValidator(QtGui.QDoubleValidator(bottom=0.,top=1000.))
        self.paramTabs.addTab(self.numericalTab, "")
        self.rotorTab = QtWidgets.QWidget()
        self.rotorTab.setObjectName("rotorTab")
        self.initBurstLabel = QtWidgets.QLabel(self.rotorTab)
        self.initBurstLabel.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.initBurstLabel.setObjectName("initBurstLabel")
        self.initBurstEdit = QtWidgets.QLineEdit(self.rotorTab)
        self.initBurstEdit.setGeometry(QtCore.QRect(180, 10, 113, 20))
        self.initBurstEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.initBurstEdit.setObjectName("initBurstEdit")
        self.initBurstEdit.setValidator(QtGui.QDoubleValidator(bottom=0.,top=100.))
        self.initLengthEdit = QtWidgets.QLineEdit(self.rotorTab)
        self.initLengthEdit.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.initLengthEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.initLengthEdit.setObjectName("initLengthEdit")
        self.initLengthEdit.setValidator(QtGui.QDoubleValidator(bottom=0.))
        self.initLengthLabel = QtWidgets.QLabel(self.rotorTab)
        self.initLengthLabel.setGeometry(QtCore.QRect(10, 30, 161, 16))
        self.initLengthLabel.setObjectName("initLengthLabel")
        self.initPowerEdit = QtWidgets.QLineEdit(self.rotorTab)
        self.initPowerEdit.setGeometry(QtCore.QRect(180, 50, 113, 20))
        self.initPowerEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.initPowerEdit.setObjectName("initPowerEdit")
        self.initPowerEdit.setValidator(QtGui.QDoubleValidator(bottom=0.,top=100.))
        self.initPowerLabel = QtWidgets.QLabel(self.rotorTab)
        self.initPowerLabel.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.initPowerLabel.setObjectName("initPowerLabel")
        self.initChannelsEdit = QtWidgets.QLineEdit(self.rotorTab)
        self.initChannelsEdit.setGeometry(QtCore.QRect(180, 70, 113, 20))
        self.initChannelsEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.initChannelsEdit.setObjectName("initChannelsEdit")
        self.initChannelsEdit.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp("^\\d{1,1}(?:\\,\\d{1,2}){0,15}$")))
        self.initChannelsLabel = QtWidgets.QLabel(self.rotorTab)
        self.initChannelsLabel.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.initChannelsLabel.setObjectName("initChannelsLabel")
        self.paramTabs.addTab(self.rotorTab, "")

        self.retranslateUi(mainWindow)
        self.paramTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Form"))
        self.consoleBox.setTitle(_translate("mainWindow", "Console"))
        self.outDirLabel.setText(_translate("mainWindow", "Output Directory"))
        self.browseButton.setText(_translate("mainWindow", "Browse..."))
        self.realTimeBox.setTitle(_translate("mainWindow", "Real Time"))
        self.realHLabel.setText(_translate("mainWindow", "h (m)"))
        self.realULabel.setText(_translate("mainWindow", "u (m/s)"))
        self.timeElapsedLabel.setText(_translate("mainWindow", "Time (h)"))
        self.tempLabel.setText(_translate("mainWindow", "Temp (C)"))
        self.sustainedSettings.setTitle(_translate("mainWindow", "Sustained Run"))
        self.sustainedStartButton.setText(_translate("mainWindow", "Start"))
        self.targetULabel.setText(_translate("mainWindow", "Target u_{rms}"))
        self.targetUUnits.setText(_translate("mainWindow", "m/s"))
        self.actualULabel.setText(_translate("mainWindow", "Actual u_{rms}"))
        self.actualUUnits.setText(_translate("mainWindow", "m/s"))
        self.targetTimeLabel.setText(_translate("mainWindow", "Exp. runtime"))
        self.targetTimeUnits.setText(_translate("mainWindow", "h"))
        self.periodSettings.setTitle(_translate("mainWindow", "Period Determination"))
        self.periodStartButton.setText(_translate("mainWindow", "Start"))
        self.targetTLabel.setText(_translate("mainWindow", "T multiplier"))
        self.targetTUnits.setText(_translate("mainWindow", "x"))
        self.targetTEdit.setText(_translate("mainWindow","1"))
        self.actualTLabel.setText(_translate("mainWindow", "Oscillation T"))
        self.actualTUnits.setText(_translate("mainWindow", "s"))
        self.densityLabel.setText(_translate("mainWindow", "Water density (kg/m^3)"))
        self.densityEdit.setText(_translate("mainWindow", "997"))
        self.areaFactorLabel.setText(_translate("mainWindow", "Res-to-Duct factor"))
        self.areaFactorEdit.setText(_translate("mainWindow", "1.9641"))
        self.paramTabs.setTabText(self.paramTabs.indexOf(self.physicalTab), _translate("mainWindow", "Physical"))
        self.fbackVelLabel.setText(_translate("mainWindow", "Feedback velocity"))
        self.fbackVelEdit.setText(_translate("mainWindow", "0.1"))
        self.fbackAccLabel.setText(_translate("mainWindow", "Feedback acceleration"))
        self.fbackAccEdit.setText(_translate("mainWindow", "0.1"))
        self.pressureSampleLabel.setText(_translate("mainWindow", "Pressure sample rate (hz)"))
        self.pressureSampleEdit.setText(_translate("mainWindow", "10"))
        self.sinSampleLabel.setText(_translate("mainWindow", "Sin-wave sample rate (hz)"))
        self.sinSampleEdit.setText(_translate("mainWindow", "100"))
        self.paramTabs.setTabText(self.paramTabs.indexOf(self.numericalTab), _translate("mainWindow", "Numerical"))
        self.initBurstLabel.setText(_translate("mainWindow", "Initial burst power (%)"))
        self.initBurstEdit.setText(_translate("mainWindow", "30"))
        self.initLengthEdit.setText(_translate("mainWindow", "3"))
        self.initLengthLabel.setText(_translate("mainWindow", "Initial burst length (s)"))
        self.initPowerEdit.setText(_translate("mainWindow", "30"))
        self.initPowerLabel.setText(_translate("mainWindow", "Initial power (%)"))
        self.initChannelsEdit.setText(_translate("mainWindow", "0,1"))
        self.initChannelsLabel.setText(_translate("mainWindow", "Channels (#,#,#,...,#)"))
        self.paramTabs.setTabText(self.paramTabs.indexOf(self.rotorTab), _translate("mainWindow", "Rotors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

